### ISSUE TITLE
Watcher stops working

### ISSUE THREAD

**Issue by mschumacher69** [RandomEngy/VidCoder#1111]
### Problem Description

Watcher works for a few files but then stops picking up new files until I disable and re-enable it. Sometimes it shows a new file with Status Planned but never encodes it.

### What version of VidCoder are you running?

8.21

**Comment by RandomEngy** [comment]
Can you send me the most recent Watcher.txt file from %appdata%\VidCoder\Logs ?

**Comment by mschumacher69** [comment]
There you go.
[2023-01-22 10.25.53 Watcher.txt](https://github.com/RandomEngy/VidCoder/files/10511319/2023-01-22.10.25.53.Watcher.txt)

**Comment by mschumacher69** [comment]
Here's an example of files being added as planned but it never adds them to the queue to start encoding them.
![image](https://user-images.githubusercontent.com/461871/215117449-76c6df07-dd51-4d78-b383-3351c6437cda.png)

This happened after VidCoder rebooted to update from 8.21 to 8.22. Before that, watcher was stuck doing nothing and after it updated and rebooted, it detected the new files but added them as planned.

It only queued them and started encoding after I disabled and re-enabled watcher.

**Comment by RandomEngy** [comment]
Hmm I didn't see any errors logged in that file. Was that the latest file after stopping and restarting the Watcher? Ideally it would be from when the watcher has stopped working.

Also, could you check the General tab in the Logs window? Does it log `# Processing file watcher queue request` when the items are added?

And is this only an issue during app updates?

**Comment by mschumacher69** [comment]
No, this was the latest file while the watcher was stuck, before I had stopped and restarted it.

I only restarted it when it added the new files as Status Planned after the update. The issue does not only occur during app updates, I was only describing that even after the app rebooted after an update, watcher only added new files as Status Planned and I had to restart watcher for it to actually add the new files to the queue and start encoding.

After the app updated, it seems to have added missing data from the previous run to the same watcher file, here's an extract with an error:
Detected new file: E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4
Could not get file info to check if it passes the picker.
System.IO.FileNotFoundException: Could not find file 'E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4'.
File name: 'E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4'
   at System.IO.FileInfo.get_Length()
   at VidCoderCommon.Utilities.CommonFileUtilities.FilePassesPickerFilter(FileInfo file, PickerFileFilter filter)
   at VidCoderFileWatcher.Services.WatcherService.FilePassesPicker(WatchedFolder watchedFolder, String filePath)
Checking lock for files pending write complete
E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4 is no longer locked
E:\Videos\.Downloads\Videos\.Encoding\Slasher.23.01.27.AD.1080p.MP4-WRC.mp4 is no longer locked
E:\Videos\.Downloads\Videos\.Encoding\See.23.01.27.LB.1080p.MP4-WRC.mp4 is no longer locked
E:\Videos\.Downloads\Videos\.Encoding\Notre-Dame.23.01.27.HM.1080p.MP4-WRC.mp4 is no longer locked
E:\Videos\.Downloads\Videos\.Encoding\NOS4A2.23.01.27.OR.1080p.MP4-WRC.mp4 is no longer locked
E:\Videos\.Downloads\Videos\.Encoding\Taken.23.01.26.DJ.1080p.MP4-WRC.mp4 is no longer locked
Sending video(s) to be queued with picker 'Watcher' and preset 'H.265 MKV 1080p Audio Passthrough':
    E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Slasher.23.01.27.AD.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\See.23.01.27.LB.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Notre-Dame.23.01.27.HM.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\NOS4A2.23.01.27.OR.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Taken.23.01.26.DJ.1080p.MP4-WRC.mp4
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
Checking lock for files pending write complete
[End File]

Then it created 2 new watcher files:
2023-01-27 17.52.06 Watcher.txt
Refreshing file list...
Enumerating folder: E:\Videos\.Downloads\Videos\.Encoding
    E:\Videos\.Downloads\Videos\.Encoding\NOS4A2.23.01.27.OR.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Notre-Dame.23.01.27.HM.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\See.23.01.27.LB.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Slasher.23.01.27.AD.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Taken.23.01.26.DJ.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4
Removing entries for file(s) that no longer exist:
    E:\Videos\.Downloads\Videos\.Encoding\Vikings.21.09.13.J.1080p.MP4-NBK\Vikings.21.09.13.J.1080p.MP4-NBK.mp4   
Detected removed files:
    E:\Videos\.Downloads\Videos\.Encoding\Vikings.21.09.13.J.1080p.MP4-NBK\Vikings.21.09.13.J.1080p.MP4-NBK.mp4   
Notifying main process of removed files.
Starting FolderWatcher for E:\Videos\.Downloads\Videos\.Encoding

2023-01-27 18.01.47 Watcher.txt
Refreshing file list...
Enumerating folder: E:\Videos\.Downloads\Videos\.Encoding
    E:\Videos\.Downloads\Videos\.Encoding\NOS4A2.23.01.27.OR.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Notre-Dame.23.01.27.HM.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\See.23.01.27.LB.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Slasher.23.01.27.AD.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Taken.23.01.26.DJ.1080p.MP4-WRC.mp4
    E:\Videos\.Downloads\Videos\.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4
Notifying main process of removed files.
Starting FolderWatcher for E:\Videos\.Downloads\Videos\.Encoding

Regarding the General tab in the Logs window, it does currently log # Processing file watcher queue request, but this is after I disabled and re-enabled watcher. I'll keep monitoring what it logs after it stops working.

**Comment by RandomEngy** [comment]
I'm interested if it logs the `Processing file watcher queue request` immediately after the files are added. Or if it only logs that after you restart the watcher. That would help narrow down the problem. From the watcher logs it looks like it's correctly trying to send the files over. I assume in this case these files were the ones that you added?

> E:\Videos.Downloads\Videos.Encoding\Witcher.23.01.27.JD.1080p.MP4-WRC.mp4
> E:\Videos.Downloads\Videos.Encoding\Slasher.23.01.27.AD.1080p.MP4-WRC.mp4
> E:\Videos.Downloads\Videos.Encoding\See.23.01.27.LB.1080p.MP4-WRC.mp4
> E:\Videos.Downloads\Videos.Encoding\Notre-Dame.23.01.27.HM.1080p.MP4-WRC.mp4
> E:\Videos.Downloads\Videos.Encoding\NOS4A2.23.01.27.OR.1080p.MP4-WRC.mp4
> E:\Videos.Downloads\Videos.Encoding\Taken.23.01.26.DJ.1080p.MP4-WRC.mp4

When they were added, did the Watcher window show them as Planned, or show nothing at all?

**Comment by mschumacher69** [comment]
Ok I will keep monitoring the log, so far it's been working fine since I disabled and re-enabled it after the last update, it processed and encoded 4 new files, I will see how long it keeps working and report back when/if it stops working.

Regarding those 6 files above, those are the 6 new files that it didn't do anything about before the update (didn't even show them as planned), it then showed them as planned right after the update but never added them to the queue and then only added them to the queue after I disabled and re-enabled watcher and it's been working fine since then so far.

**Comment by RandomEngy** [comment]
One more question that may help me investigate: The files that showed up as "planned" but were not in the queue: When did they first show up in the Watcher window? After they were added to the folder? Or after an app restart?

**Comment by mschumacher69** [comment]
They only showed up as planned in the watcher window after the app restart and were only added to the queue after I disabled and re-enabled watcher.

Before the app restart, no new files were showing in watcher.

**Comment by RandomEngy** [comment]
I added some more logging for the main process in 8.23, but you'll need to turn it on with Global Options -> Advanced -> Logging Verbosity -> Extended. That should give me a better idea of how far it's getting and why it isn't immediately queueing up the files on re-launch.

**Comment by mschumacher69** [comment]
Ok I updated and enabled it, I will report back once it stops working.

Just to clarify, watcher wasn't only not immediately queueing up the files on re-launch, it used to happen while the app is running as well. It would work for a while queuing new files but then after a few days stop working (on the same run) until I disable and re-enable watcher.

This hasn't happened yet since I updated to 8.22 and now 8.23, it's been working fine since then, but it usually takes a few days to stop working, so let's wait and see.

**Comment by RandomEngy** [comment]
I made a significant fix in 8.24, which resolves problems with tracking folder moves.

**Comment by mschumacher69** [comment]
Great, yeah that must have been my issue because my downloads are all in folders and they get auto moved into the watched folder on download completion.

I will let you know if I'm still facing issues.

**Comment by mschumacher69** [comment]
Ok so it's still happening. It worked for 7 files until yesterday, but it didn't detect today's file (NS.23.02.04.mp4) until I disabled and re-enabled watcher.

I attached logs before and after disabling and re-enabling watcher. As you can see in the logs, NS.23.02.04.mp4 is nowhere to be found in the logs before I disabled and re-enabled watcher, and it only appeared in the logs after I disabled and re-enabled watcher.
[2023-02-02 08.09.02 Watcher (before restarting watcher).txt](https://github.com/RandomEngy/VidCoder/files/10608773/2023-02-02.08.09.02.Watcher.before.restarting.watcher.txt)
[2023-02-04 16.05.39 Watcher (after restrating watcher).txt](https://github.com/RandomEngy/VidCoder/files/10608774/2023-02-04.16.05.39.Watcher.after.restrating.watcher.txt)
[VidCoder Log (after restarting watcher).txt](https://github.com/RandomEngy/VidCoder/files/10608775/VidCoder.Log.after.restarting.watcher.txt)
[VidCoder Log (before restarting watcher).txt](https://github.com/RandomEngy/VidCoder/files/10608776/VidCoder.Log.before.restarting.watcher.txt)

**Comment by RandomEngy** [comment]
It looks like the operating system just didn't fire the listener I registered. Is the E: drive a mounted network drive? The only thing I can think of to do about this is add a backup system that periodically reads the contents of the folder, though I'm not a fan of adding the additional complexity for something that just should be working.

**Comment by mschumacher69** [comment]
No, E: is an internal drive.

**Comment by mschumacher69** [comment]
Again, worked for a few files then stopped working. This time it showed a file as planned in the watcher window but never added it to the queue and didn't show or add any further files since then.

Nothing interesting in the general log, the watcher log show the following about the last file which shows as planned in watcher bat was never added to the queue:
`Detected new file/folder: E:\Videos\.Downloads\Videos\.Encoding\Si.18.10.25.1080p.MP4-KTM[rarbg]
Path is a folder. Searching for video sources inside.
Detected new file/folder: E:\Videos\.Downloads\Videos\.Encoding\Si.18.10.25.1080p.MP4-KTM[rarbg]\RARBG.txt
Detected new file/folder: E:\Videos\.Downloads\Videos\.Encoding\Si.18.10.25.1080p.MP4-KTM[rarbg]\si.18.10.25.mp4
Detected new file/folder: E:\Videos\.Downloads\Videos\.Encoding\Si.18.10.25.1080p.MP4-KTM[rarbg]\si.18.10.25.nfo
Checking lock for files pending write complete
E:\Videos\.Downloads\Videos\.Encoding\Si.18.10.25.1080p.MP4-KTM[rarbg]\si.18.10.25.mp4 is no longer locked
Sending video(s) to be queued with picker 'Watcher' and preset 'H.265 MKV 1080p Audio Passthrough':
    E:\Videos\.Downloads\Videos\.Encoding\Si.18.10.25.1080p.MP4-KTM[rarbg]\si.18.10.25.mp4`

**Comment by RandomEngy** [comment]
Do you have Extended logging enabled? That would enable additional logging on the main process side that might help explain why it was sent by the watcher but not queued.

**Comment by mschumacher69** [comment]
Yes I have, nothing out of the ordinary in there. The log files that I attached earlier are extended.

**Comment by RandomEngy** [comment]
The logs from earlier showed that the system file watcher failed. In this case the file watcher worked, but something went wrong with the transfer over to the main process. You said there was absolutely nothing in the General log in that case?

**Comment by mschumacher69** [comment]
Wait, I found this error in the General log, not sure if it helps:
`# Sending Request
  CallId: 4465
  MethodName: Ping
ERROR: Invalid total progress fraction calculated.
Total queue cost: 9132.68
Completed queue work: 1495.24
In progress work: 121844
Completed items: 1
ERROR: Queue item 0: Cost: 1495.24 Video Length: 00:24:55.2400000 Completed: True
ERROR: Queue item 1: Cost: 1218.44 Video Length: 00:20:18.4400000 Completed: False
ERROR: Queue item 2: Cost: 1574.2 Video Length: 00:26:14.2000000 Completed: False
ERROR: Queue item 3: Cost: 1509.92 Video Length: 00:25:09.9200000 Completed: False
ERROR: Queue item 4: Cost: 1736.64 Video Length: 00:28:56.6400000 Completed: False
ERROR: Queue item 5: Cost: 1598.24 Video Length: 00:26:38.2400000 Completed: False
# Sending Request
  CallId: 4466
  MethodName: Ping`

**Comment by mschumacher69** [comment]
Here's another one:
```
# Sending Request
  CallId: 1871
  MethodName: Ping
ERROR: Invalid total progress fraction calculated.
Total queue cost: 18929.499
Completed queue work: 11600.008
In progress work: 201552
Completed items: 7
ERROR: Queue item 0: Cost: 2077.96 Video Length: 00:34:37.9600000 Completed: True
ERROR: Queue item 1: Cost: 2480.812 Video Length: 00:41:20.8120000 Completed: True
ERROR: Queue item 2: Cost: 1291.926 Video Length: 00:21:31.9260000 Completed: True
ERROR: Queue item 3: Cost: 1575.915 Video Length: 00:26:15.9150000 Completed: True
ERROR: Queue item 4: Cost: 1303.64 Video Length: 00:21:43.6400000 Completed: True
ERROR: Queue item 5: Cost: 1467.435 Video Length: 00:24:27.4350000 Completed: True
ERROR: Queue item 6: Cost: 1402.32 Video Length: 00:23:22.3200000 Completed: True
ERROR: Queue item 7: Cost: 2015.52 Video Length: 00:33:35.5200000 Completed: False
ERROR: Queue item 8: Cost: 1548.6 Video Length: 00:25:48.6000000 Completed: False
ERROR: Queue item 9: Cost: 2359.44 Video Length: 00:39:19.4400000 Completed: False
ERROR: Queue item 10: Cost: 1405.931 Video Length: 00:23:25.9310000 Completed: False
```

**Comment by RandomEngy** [comment]
Thanks. That's an unrelated issue though; I'm working on getting it fixed.

The log entries I'm interested in are `Processing file watcher queue request` and anything immediately following them. That indicates that the main process received the queue request.

**Comment by mschumacher69** [comment]
Yeah you're right, those errors are from after I restarted watcher.

Here's a log file from the last time it successfully queued a file (si.18.11.18.mp4) till the time I restarted it where it successfully queued si.18.10.25.mp4 (after CallId: 11242).

si.18.10.25.mp4 is the file which was showing as planned until I restarted watcher, so it showed as planned between the last successfully queued file (si.18.11.18.mp4) and CallId: 11242, but it is not showing anything in the log about that.
[Log.txt](https://github.com/RandomEngy/VidCoder/files/10668785/Log.txt)

**Comment by mschumacher69** [comment]
@RandomEngy I think this is happening when it scans a .mp4 file that is still downloading but hasn't completed yet. It adds it as planned but never processes it once it's complete and it stops adding any further files after that until I restart watcher.

**Comment by RandomEngy** [comment]
It looks like the General log doesn't have the interesting part, since the request to queue was never sent from the watcher process. In this case with Watcher log is what I would need. The watcher has code to periodically check if the file is locked (downloading) and to queue it when it's ready. If there something going wrong with that, it would be in the Watcher log.

**Comment by mschumacher69** [comment]
I attached several watcher logs above, check the last one I posted 3 weeks ago.

**Comment by RandomEngy** [comment]
I wasn't sure if those were from a different run or a different issue. In those earlier logs the operating system file watcher never notified VidCoder of the new file.

**Comment by mschumacher69** [comment]
So how to fix the issue?

**Comment by RandomEngy** [comment]
The clean way would be to ask Windows to fix the issue.

The only way I could resolve it would be to do polling and re-scan the whole folder periodically to see if I find new files that the OS file watcher didn't tell me about. I'm not crazy about that one as it means extra work for everyone whose system is working correctly. So it would also entail another configuration option for the watcher. But right now all configuration is right on the main window, and such an option would be confusing clutter for most users. Maybe I could shove it in Advanced under the Global Options...

It would be a decent-sized feature and I'm working on some other projects right now. I'll probably give it more priority if anyone else reports the issue as well.

**Comment by mschumacher69** [comment]
Its been reported before since beta, issue 1 in #1064.

**Comment by RandomEngy** [comment]
I don't know if that's the same issue, as I never got logs from that person. That might have been a different issue that I've already fixed, where folder moves were not being detected.

**Comment by redrules70** [comment]
I can confirm,it is the same issue....Sorry,i was unable to sent any logs,but i watched the topic,and fellow member mschumacher69 described his (and mine) problem,with much more details/accurate

**Comment by RandomEngy** [comment]
I agree they have similar symptoms, but I was hoping for the logs to confirm that the underlying cause is the same.

**Comment by redrules70** [comment]
So,there in nothinng can be done?

**Comment by RandomEngy** [comment]
You could give me some logs so I can properly investigate your issue...

**Comment by mschumacher69** [comment]
So @redrules70 are you still having the same issue on the latest stable version?

**Comment by redrules70** [comment]
Yes,in all versions.Up to 8.24

**Comment by redrules70** [comment]
And now i'm testing 8.25

**Comment by mschumacher69** [comment]
Ok, so it is indeed the same issue, @RandomEngy it's not a different issue that you've already fixed, where folder moves were not being detected, otherwise he wouldn't have had the issue up to 8.24.

So @redrules70 post your watcher log when it happens. It's easy, just navigate to %appdata%\VidCoder\Logs (just paste this in your windows search bar and hit enter) and search for watcher and upload the latest Watcher.txt, the file name starts with a date and then a number, for example 2023-02-25 22.11.51 Watcher.txt.

**Comment by redrules70** [comment]
So far the same behavior.....It only "improves",if i PAUSE the encoding process while watcher is running..And i say "improves",because it only delays the not-adding problem ..I have AMD Ryzen 5700g,32gb Ram,3 parallel processes at 88%
I'm still testing

**Comment by redrules70** [comment]
Nope,still the same...I guess,i'll skip watch-folder function,and i will use the program as before

**Comment by mschumacher69** [comment]
Why don't you provide logs so David can investigate??

**Comment by redrules70** [comment]
1st method: Copy all files from hdd to hdd with teracopy .Result the watcher.1st Try 
2nd method : Copy all files from hdd to hdd with Win10 copy .Result the watcher 2nd try
3rd method : Copy all files,to watch-folder from source directory,SAME hdd.. Result the watcher.3rd try
4th method: Move all files,to watch-folder from source directory,SAME hdd.. Result the watcher.4th try

The watcher stops adding files on queue,in all cases...
in the 4th method.it just adds up more files,but eventually stops

If you go to Vidcoder-Logs folder while watching/queing/encoding,you'll see the watcher file properties (date modified,size (as they should))...

[2023-02-28 16.34.30 Watcher 4th TRY.txt](https://github.com/RandomEngy/VidCoder/files/10851898/2023-02-28.16.34.30.Watcher.4th.TRY.txt)
[2023-02-28 14.36.16 Watcher 1st TRY.txt](https://github.com/RandomEngy/VidCoder/files/10851900/2023-02-28.14.36.16.Watcher.1st.TRY.txt)
[2023-02-28 15.07.23 Watcher 2nd TRY.txt](https://github.com/RandomEngy/VidCoder/files/10851901/2023-02-28.15.07.23.Watcher.2nd.TRY.txt)
[2023-02-28 15.42.37 Watcher 3rd TRY.txt](https://github.com/RandomEngy/VidCoder/files/10851902/2023-02-28.15.42.37.Watcher.3rd.TRY.txt)

**Comment by redrules70** [comment]
The same behavior,instead of copyping/moving,when downloading....Just Slower

**Comment by RandomEngy** [comment]
When you say "stops adding files" what is the last one you saw added? For example on that 1st try, the watcher sent 168-173 to be encoded, then 001-010. Did those ones show up as queued in the main window? Or were there other files copied beyond these that the watcher just never saw?

**Comment by redrules70** [comment]
The watcher sent 16 of 173 files to queue (167-173,001-010).Vidcoder encoded these files,but all the other files copied to watch-folder were simply ignored...In the other tries,same behavior,just different number of files

**Comment by RandomEngy** [comment]
Alright, I'll see if I can implement an alternate "polling" mode to look for the files, since it appears that on some systems the file watcher just doesn't work. Typescript also has this configuration where you can use the polling or the file watcher. Might not happen right away; I need to get to a good stopping point with another project.

**Comment by RandomEngy** [comment]
The polling mode is implemented in v9 Beta. (Global options -> Advanced -> Watcher mode)

**Comment by redrules70** [comment]
Hello again,and thanks for the new version!!!
It works MUCH better now,but now flawlessly (in my opinion)..
Yes,the watch now "grabs" everything i throw,but all the files status 'planned' are NOT going to the main encoding window..
Is this normal? their status will change from 'planned" to "queued" eventually?
sorry,i didn't test it for many hours..

still testing

p.s. i tried everything i could think of (copying/moving/downloading),except restarting the watcher..

**Comment by redrules70** [comment]
Hmmm...An observation....While adding files in the watch-folder,i saw the watcher panel adding the file(s) as "planned" -normal,but in the main encoding panel,the line which shows "adding files" progress starts/stops IMMEDIATELY.

**Comment by RandomEngy** [comment]
I think that might be because I forgot to check if the file was locked before sending it to be queued. That should be fixed in 9.1 Beta; give it another try.

**Comment by redrules70** [comment]
Final (?) Thoughts:

In 9.1 beta,the worker FINALLY works!!! it recognises any change in watch-folder ..

But the problem still lies somewhere else (at least in my end)..
The watch-folder contains 315 files..If i add them manually (dragged them from win explorer),or throught the watcher,all i have in queue is 255 files..And yes,the watcher will add new files (if recognises them)

The only way to have 315 files in queue is to go back in stable 7.15,or 8.07beta (the watcher not woirking,as it is now)...
I know,but these are the only versions they recognise 315 files.Something must have happened to Handbrake Core...
I don't plan to install codec packs (not required)..
If you can think anything...
But so much appreciation for your efforts!!! I will continue to update the beta version,just in case....Even,maybe a new windows installation....

**Comment by RandomEngy** [comment]
That's good to hear. Though what did you mean by "disabling DVD reading"?

**Comment by redrules70** [comment]
Global options->Advanced->DVD reading.....At the bottom...
I know,totally weird...never happened with the "good" versions

**Comment by RandomEngy** [comment]
Ahh, you disabled LibDVDNav. That's a library that's used to find video titles on a DVD. When disabled it uses an alternate way of finding the titles. So the version of LibDVDNav included with the HandBrake core I was using must have had some trouble with those titles.

**Comment by mschumacher69** [comment]
Ok so I've been monitoring this and it only happens when there's a file still being written, it adds it as planned and never adds starts the encoding or add any further files afterwards.

So the issue is that Watcher doesn't seem to properly detect when a file is not being written anymore to start the encoding process.

P.S.: This is using the regular watcher, not the polling mode added to the beta.

**Comment by RandomEngy** [comment]
@mschumacher69 I need the General and Watcher log files to be able to help you here.

**Comment by mschumacher69** [comment]
@RandomEngy I had already sent several General and Watcher log files above, no change in the log files since then.

**Comment by mschumacher69** [comment]
@RandomEngy I think it would be easier if you try to replicate it on your side, use [vidcoder](https://vidcoder.net/) to encode a file into a watched folder and you'll see the issue in action.

**Comment by RandomEngy** [comment]
I cannot reproduce it on my side, which is why I need the logs. I've also already looked at all the logs posted in this thread, and have made some fixes and logging changes since then. Why don't you create a new issue and post your logs there; this catch-all watcher thread has gotten a bit too long to manage.
