### ISSUE TITLE
[BUG] Vidcoder does not decode in QSV when encoder is set to H265 QSV

### ISSUE THREAD

**Issue by ZaphodX77** [RandomEngy/VidCoder#267]
Handbrake has this problem only when a 10bit source file is selected. I filed Handbrake #873 opened on Aug 26 by ZaphodX77. It was determined that Handbrake substantially worked, with the 10bit source file exception. Please see #873 for logs & comments. Handbrake has the QSV decoder switches on a separate page, rather than the decoder page, with 2 switches now for the nightlies. It could be that this relocation & 2 switch thing is Vidcoder's problem. I did not test for this bug until I got my Kaby Lake processor, so I am late in reporting this. I also thought that Handbrake would be fixed by now.

[BUG] Vidcoder does not turn on the QSV decoding whenever H265 QSV is selected as the output. 

[Feature Request] Please give Vidcoder the capability to turn QSV decoding on when doing software decodes like Handbrake does. This reduces energy consumption & speeds up software encodes.

**Comment by RandomEngy** [comment]
The QSV decode issue for H265 should be fixed in 2.61.

**Comment by ZaphodX77** [comment]
Unfortunately, it's still not fixed. I think that the 2 switches that Handbrake has are the problem.
"HWDecode": false,
    "QSV": {
      "Decode": true,"

See below from the partial log.

  "Video": {
    "Encoder": 512,
    "Level": "4.0",
    "TwoPass": false,
    "Turbo": false,
    "ColorMatrixCode": 0,
    "Options": "",
    "Preset": "balanced",
    "Profile": "main",
    "Quality": 28.0,
    "OpenCL": false,
    "HWDecode": false,
    "QSV": {
      "Decode": true,
      "AsyncDepth": 0
    }
  }
}
[15:19:08] starting job
[15:19:08] work: track 1, dithering not supported by codec
[15:19:08] job configuration:
[15:19:08]  * source
[15:19:08]    + C:\Temp1\Test.mkv
[15:19:08]    + title 1, chapter(s) 1 to 8
[15:19:08]    + container: matroska,webm
[15:19:08]  * destination
[15:19:08]    + C:\Temp1\Test X265 K28.mkv
[15:19:08]    + container: Matroska (libavformat)
[15:19:08]      + chapter markers
[15:19:08]  * video track
[15:19:08]    + decoder: hevc

Still not decoder: hevc_qsv. I have a i7-7770K Kaby Lake processor, which can also decode 10bit. It did not work for 8bit or 10bit. Please allow me to test for you.

**Comment by RandomEngy** [comment]
I just checked and it looks like we're properly passing in "Decode": true when using H265 QSV encoding, and that it's properly picking it up as a decoder. I still need to restart the betas and update to have it use the QSV decoder in all cases.
