### ISSUE TITLE
BUG: 4.13-beta - status bar doesn't update after new queue additions

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#402]
![image](https://user-images.githubusercontent.com/14026600/45848661-31de0780-bce4-11e8-9762-6a65e8cd0658.png)

**Comment by RandomEngy** [comment]
I've been looking over the code and don't see an obvious way this could happen. Do you have a set of steps to reproduce it?

Are you using the CLI to encode jobs?

**Comment by bcurran3** [comment]
No. I always drag and drop from File Explorer.

It is a big queue. Possibly pushed over scope for the variables? (Doubt it. Just throwing something out.)

**Comment by bcurran3** [comment]
I just quit VidCoder and restarted it. Seems to have re-adjusted the values:

![image](https://user-images.githubusercontent.com/14026600/45863170-cfa7f580-bd29-11e8-8a86-e87e38f96a59.png)

**Comment by RandomEngy** [comment]
I just released 4.14 Beta, which has refactored how I handle total queue progress. It should now dump a bunch of diagnostic information into the log if it sees a total percentage above 100%. If this ever happens again, it would be very helpful to post the log here.

**Comment by bcurran3** [comment]
Thanks. I'm still running 4.13-beta and just got it again. Will cancel and run with 4.14-beta later today.

Kinda funny actually:
![image](https://user-images.githubusercontent.com/14026600/45965391-2f79f700-bfdd-11e8-8880-d0836cfdfb0a.png)

**Comment by bcurran3** [comment]
Still have the problem in 4.14-beta:


![image](https://user-images.githubusercontent.com/14026600/46033953-4fc8b500-c0b4-11e8-8ead-310f0a0147da.png)

**Comment by RandomEngy** [comment]
Great, can you copy your log to pastebin and share it?

**Comment by bcurran3** [comment]
Point me to which log file would be useful please. On the machine in question I have 10,653 log files of which they're based on the individual files that have been transcoded. Is there a program specific log file somewhere that I'm not seeing?

**Comment by RandomEngy** [comment]
Windows -> Log

**Comment by bcurran3** [comment]
I don't have a c:\Windows\Log folder. I do have a c:\Windows\Logs folder, but none of the 9 folders in there identify themselves with VidCoder by name.

**Comment by RandomEngy** [comment]
No I mean the "Windows" button on the ribbon, then the Log window. You can also find it by going to %appdata%\VidCoder-Beta\Logs and finding the latest log file that's just a date. This is the general app log file. Anyway somewhere in there should be diagnostic data that says what's going wrong.

**Comment by bcurran3** [comment]
![image](https://user-images.githubusercontent.com/14026600/46324313-a435ce00-c5a7-11e8-8794-8d88fdaeaec3.png)


First let me comment that there were never that many files in the queue. The numbers are completely off. There was a failure of a few hundred(?) files when a network share went offline. Between right clicking and telling it to re-add the failures to the queue, killing the program when it went unresponsive, restarting it and watching it being unresponsive again, and maybe a repeat of this whole scenario.... The Completed list has the same 4 files (I have 4 worker processes configured) repeatedly failed over and over and over for pages and pages in the list. Then another set of 4 files repeated over and over and over again in the list. 

I'll try to dig up the log later. Right now when I try...."VidCoder Beta - 779.3% (Not Responding). I need to  tune down my worker process priority and try again later.
